laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('somos-ativa', ['as' => 'somos-ativa', 'uses' => 'SomosAtivaController@index']);
Route::get('filosofia/{passo?}', ['as' => 'filosofia', 'uses' => 'FilosofiaController@index']);
Route::get('ativa-wealth', ['as' => 'ativa-wealth', 'uses' => 'AtivaWealthController@index']);
Route::get('carta-ativa-wm', ['as' => 'carta-ativa-wm', 'uses' => 'CartaAtivaController@index']);
Route::get('imprensa', ['as' => 'imprensa', 'uses' => 'ImprensaController@index']);
Route::get('imprensa/{imprensa_slug}', ['as' => 'imprensa.show', 'uses' => 'ImprensaController@show']);
Route::get('politicas', ['as' => 'politicas', 'uses' => 'PoliticasController@index']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);

    Route::patch('home/background/{home_bg}', [
        'as'   => 'painel.home.background',
        'uses' => 'HomePageController@updateBg'
    ]);
    Route::resource('home', 'HomePageController');

    Route::resource('somos-ativa', 'SomosAtivaController', ['only' => ['index', 'update']]);
    Route::resource('filosofia', 'FilosofiaController', ['only' => ['index', 'update']]);
    Route::resource('ativa-wealth', 'AtivaWealthController', ['only' => ['index', 'update']]);

    Route::patch('imprensa/background/{imprensa_bg}', [
        'as'   => 'painel.imprensa.background',
        'uses' => 'ImprensaController@updateBg'
    ]);
    Route::resource('imprensa', 'ImprensaController');
    Route::get('imprensa/{imprensa}/imagens/clear', [
        'as'   => 'painel.imprensa.imagens.clear',
        'uses' => 'ImprensaImagensController@clear'
    ]);
    Route::resource('imprensa.imagens', 'ImprensaImagensController');

    Route::resource('politicas', 'PoliticasController', ['only' => ['index', 'update']]);
    Route::resource('documentos/categorias', 'DocumentosCategoriasController');
    Route::resource('documentos', 'DocumentosController');

    Route::patch('carta-ativa-wm/background/{cartaAtiva_bg}', [
        'as'   => 'painel.carta-ativa-wm.background',
        'uses' => 'CartaAtivaController@updateBg'
    ]);
    Route::resource('carta-ativa-wm', 'CartaAtivaController');

    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController', ['only' => ['index', 'update']]);

    Route::resource('usuarios', 'UsuariosController');

    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Http/Controllers/Painel/AtivaWealthController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AtivaWealthRequest;
use App\Http\Controllers\Controller;

use App\Models\AtivaWealth;
use App\Helpers\CropImage;

class AtivaWealthController extends Controller
{
    private $image_config = [
        'width'  => 1980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/backgrounds/'
    ];

    public function index()
    {
        $registro = AtivaWealth::first();

        return view('painel.ativa-wealth.index', compact('registro'));
    }

    public function update(AtivaWealthRequest $request, AtivaWealth $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['background'])) {
                $input['background'] = CropImage::make('background', $this->image_config);
            }

            $registro->update($input);
            return redirect()->route('painel.ativa-wealth.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/CartaAtivaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CartaAtivaRequest;
use App\Http\Requests\CartaAtivaBgRequest;
use App\Http\Controllers\Controller;

use App\Models\CartaAtiva;
use App\Models\CartaAtivaBg;

use App\Helpers\CropImage;

class CartaAtivaController extends Controller
{
    public function index()
    {
        $arquivos = CartaAtiva::ordenados()->paginate(20);
        $cartaAtiva_background = CartaAtivaBg::first();

        return view('painel.carta-ativa-wm.index', compact('arquivos', 'cartaAtiva_background'));
    }

    public function create()
    {
        return view('painel.carta-ativa-wm.create');
    }

    public function store(CartaAtivaRequest $request)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            $input['arquivo'] = $this->uploadArquivo($input['arquivo']);

            CartaAtiva::create($input);
            return redirect()->route('painel.carta-ativa-wm.index')->with('success', 'Arquivo adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar arquivo: '.$e->getMessage()]);

        }
    }

    public function edit(CartaAtiva $arquivo)
    {
        return view('painel.carta-ativa-wm.edit', compact('arquivo'));
    }

    public function update(CartaAtivaRequest $request, CartaAtiva $arquivo)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            if (isset($input['arquivo'])) {
                $input['arquivo'] = $this->uploadArquivo($input['arquivo']);
            }

            $arquivo->update($input);
            return redirect()->route('painel.carta-ativa-wm.index')->with('success', 'Arquivo alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar arquivo: '.$e->getMessage()]);

        }
    }

    public function destroy(CartaAtiva $arquivo)
    {
        try {

            $arquivo->delete();
            return redirect()->route('painel.carta-ativa-wm.index')->with('success', 'Arquivo excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir arquivo: '.$e->getMessage()]);

        }
    }

    public function uploadArquivo($file)
    {
        $filePath = 'assets/arquivos/';
        $fileName = preg_replace("([^\w\s\d\-_~,;:\[\]\(\).])", '', $file->getClientOriginalName());
        $fileName = date('YmdHis').'_'.$fileName;

        $file->move(public_path($filePath), $fileName);
        return $fileName;
    }

    public function updateBg(CartaAtivaBgRequest $request, CartaAtivaBg $cartaAtiva_bg)
    {
        try {

            $input = array_filter($request->except(['_token', '_method']), 'strlen');

            if (isset($input['background'])) {
                $input['background'] = CropImage::make('background', [
                    'width'  => 1980,
                    'height' => null,
                    'upsize' => true,
                    'path'   => 'assets/img/backgrounds/'
                ]);
            }

            $cartaAtiva_bg->update($input);
            return back()->with('success', 'Background alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar background: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;
use App\Helpers\CropImage;

class ContatoController extends Controller
{
    private $image_config = [
        'width'  => 1980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/backgrounds/'
    ];

    public function index()
    {
        $registro = Contato::first();

        return view('painel.contato.index', compact('registro'));
    }

    public function update(ContatoRequest $request, Contato $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['background'])) {
                $input['background'] = CropImage::make('background', $this->image_config);
            }

            $registro->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DocumentosCategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DocumentoCategoriaRequest;
use App\Http\Controllers\Controller;

use App\Models\DocumentoCategoria;

class DocumentosCategoriasController extends Controller
{
    public function index()
    {
        $categorias = DocumentoCategoria::ordenados()->get();

        return view('painel.documentos.categorias.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.documentos.categorias.create');
    }

    public function store(DocumentoCategoriaRequest $request)
    {
        try {

            $input = $request->all();

            DocumentoCategoria::create($input);
            return redirect()->route('painel.documentos.categorias.index')->with('success', 'Categoria adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar categoria: '.$e->getMessage()]);

        }
    }

    public function edit(DocumentoCategoria $categoria)
    {
        return view('painel.documentos.categorias.edit', compact('categoria'));
    }

    public function update(DocumentoCategoriaRequest $request, DocumentoCategoria $categoria)
    {
        try {

            $input = $request->all();

            $categoria->update($input);
            return redirect()->route('painel.documentos.categorias.index')->with('success', 'Categoria alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar categoria: '.$e->getMessage()]);

        }
    }

    public function destroy(DocumentoCategoria $categoria)
    {
        try {

            $categoria->delete();
            return redirect()->route('painel.documentos.categorias.index')->with('success', 'Categoria excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir categoria: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DocumentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DocumentoRequest;
use App\Http\Controllers\Controller;

use App\Models\DocumentoCategoria;
use App\Models\Documento;

class DocumentosController extends Controller
{
    private $categorias;

    public function __construct()
    {
        $this->categorias = DocumentoCategoria::ordenados()->lists('titulo', 'id');
    }

    public function index(Request $request)
    {
        $categorias = $this->categorias;
        $filtro     = $request->query('filtro');

        if (DocumentoCategoria::find($filtro)) {
            $documentos = Documento::ordenados()->categoria($filtro)->get();
        } else {
            $documentos = Documento::join('documentos_categorias as cat', 'cat.id', '=', 'documentos_categoria_id')
                ->orderBy('cat.ordem', 'ASC')
                ->orderBy('cat.id', 'DESC')
                ->select('documentos.*')
                ->ordenados()->get();
        }

        return view('painel.documentos.index', compact('categorias', 'documentos', 'filtro'));
    }

    public function create()
    {
        $categorias = $this->categorias;

        return view('painel.documentos.create', compact('categorias'));
    }

    public function store(DocumentoRequest $request)
    {
        try {

            $input = $request->all();
            $input['arquivo'] = $this->uploadArquivo($input['arquivo']);

            Documento::create($input);
            return redirect()->route('painel.documentos.index')->with('success', 'Documento adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar documento: '.$e->getMessage()]);

        }
    }

    public function edit(Documento $documento)
    {
        $categorias = $this->categorias;

        return view('painel.documentos.edit', compact('categorias', 'documento'));
    }

    public function update(DocumentoRequest $request, Documento $documento)
    {
        try {

            $input = array_filter($request->all(), 'strlen');

            if (isset($input['arquivo'])) {
                $input['arquivo'] = $this->uploadArquivo($input['arquivo']);
            }

            $documento->update($input);
            return redirect()->route('painel.documentos.index')->with('success', 'Documento alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar documento: '.$e->getMessage()]);

        }
    }

    public function destroy(Documento $documento)
    {
        try {

            $documento->delete();
            return redirect()->route('painel.documentos.index')->with('success', 'Documento excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir documento: '.$e->getMessage()]);

        }
    }

    public function uploadArquivo($file)
    {
        $filePath = 'assets/documentos/';
        $fileName = str_slug(pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME)).'_'.date('YmdHis').'.'.$file->getClientOriginalExtension();

        $file->move(public_path($filePath), $fileName);
        return $fileName;
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class HomeController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/PoliticasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\PoliticasRequest;
use App\Http\Controllers\Controller;

use App\Models\Politicas;
use App\Helpers\CropImage;

class PoliticasController extends Controller
{
    private $image_config = [
        'width'  => 1980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/backgrounds/'
    ];

    public function index()
    {
        $registro = Politicas::first();

        return view('painel.politicas.index', compact('registro'));
    }

    public function update(PoliticasRequest $request, Politicas $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['background'])) {
                $input['background'] = CropImage::make('background', $this->image_config);
            }

            $registro->update($input);
            return redirect()->route('painel.politicas.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(str_is('painel.home*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.home.index') }}">Home</a>
    </li>

    <li @if(str_is('painel.somos-ativa*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.somos-ativa.index') }}">Somos Ativa</a>
    </li>

    <li @if(str_is('painel.filosofia*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.filosofia.index') }}">Filosofia</a>
    </li>

    <li @if(str_is('painel.ativa-wealth*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.ativa-wealth.index') }}">Ativa Wealth</a>
    </li>

    <li @if(str_is('painel.imprensa*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.imprensa.index') }}">Imprensa</a>
    </li>

    <li @if(str_is('painel.carta-ativa-wm*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.carta-ativa-wm.index') }}">Carta Ativa WM</a>
    </li>

    <li @if(str_is('painel.politicas*', Route::currentRouteName()) || str_is('painel.documentos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.politicas.index') }}">Políticas</a>
    </li>

    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url() }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/painel/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/css/jquery-ui.min.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url() }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/painel/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/bootbox.min.js') }}"></script>
    <script src="{{ asset('assets/painel/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/painel/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/js/painel.js') }}"></script>
</body>
</html>